name: Assign Issue
on:
  issues:
    types: [opened]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign Issue
        uses: pozil/auto-assign-issue@v2 #actions-ecosystem/action-assign@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: JulesMessegee