name: Assign Issue
on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  auto-assign:
    name: Auto-assign Issue
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Assign Issue
      uses: pozil/auto-assign-issue@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        assignees: JulesMessegee