name: Run Tests
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Restore dependencies
      run: dotnet restore src/HelloWorld/HelloWorld.csproj

    - name: Build
      run: dotnet build src/HelloWorld/HelloWorld.csproj --no-restore

    - name: Run tests
      run: dotnet test src/HelloWorld.Tests/HelloWorld.Tests.csproj --no-restore --verbosity normal